# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Khésis
email: balint@khesis.com
description: >- # this means to ignore newlines until "baseurl:"
  Electronic music producer based in Budapest, Hungary.
  Creating sounds bordering on the physical and the impossibly electronic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://khesis.com" # the base hostname & protocol for your site, e.g. http://example.com
spotify_id: "5yO9sut5AzxeY2Pnvwnlxr"
bandcamp_username: khesis
soundcloud_username: khesis
facebook_username: KhesisMusic
instagram_username: balintkhesis
twitter_username: khesismusic

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed

collections:
  - releases
  - mixes

collections_dir: content

defaults:
  - scope:
      path: "content/_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
